python/object-detection/README.md
python/object-detection/main.py
python/object-detection/requirements.txt

Added a demo to leverage cloud functions and detect objects in an uploaded image

doc: added object detection demo in python

---

nodejs/welcome-email/README.md
nodejs/welcome-email/index.js
nodejs/welcome-email/package.json

Cloud function demo in Nodejs leveraging the MailGun Email API to send welcome emails

Welcome Email using Cloud Functions 

---

python/file-backup/README.md
python/file-backup/main.py
python/file-backup/requirements.txt

A sample Python Cloud Function that leverages Dropbox to create backups of important files uploaded to Appwrite.

File Backup using the dropbox API

---

README.md
deno/template/README.md
deno/template/index.js
nodejs/template/README.md
nodejs/template/index.js
nodejs/template/package.json
php/template/README.md
php/template/composer.json
php/template/index.php
python/template/README.md
python/template/main.py
python/template/requirements.txt
ruby/template/Gemfile
ruby/template/README.md
ruby/template/main.rb

Templates for python. 
@eldadfux please let me if this general structure is okay and I can do the same for the other languages.

docs: functions template

---

.gitignore
nodejs/welcome-email/README.md
nodejs/welcome-email/index.js

Started work on https://github.com/appwrite/demos-for-functions/issues/16 but had trouble figuring out exactly what to do to get example working. Made changes to README to help other beginners onboard faster.

Made clarifications to README for Nodejs welcome-email.

---

dotnet/storage-cleaner/.gitignore
dotnet/storage-cleaner/Program.cs
dotnet/storage-cleaner/README.md
dotnet/storage-cleaner/StorageCleaner.csproj

Deletes files in the storage older than XX days on a schedule.
@eldadfux if you fine with this, I'll convert this script to other languages 👍🏻

adds(dotnet): storage cleaner

---

.gitignore
README.md
python/file-backup/README.md
python/file-backup/main.py
python/object-detection/README.md
python/object-detection/main.py
python/storage-cleaner/README.md
python/storage-cleaner/main.py
python/storage-cleaner/requirements.txt
python/welcome-email/README.md
python/welcome-email/main.py
python/welcome-email/requirements.txt

Relevant issues:
#19 #40
Testing:
tested `welcome-email` and `storage-cleaner` manually

feat: adding remaining python functions, removing unnecessary dependencies, standardizing env variables

---

nodejs/storage-cleaner/README.md
nodejs/storage-cleaner/index.js
nodejs/storage-cleaner/package-lock.json
nodejs/storage-cleaner/package.json

Deletes files in the storage older than XX days on a schedule.
This is in response to #38 
I've used top level await instead of working with nested promises, since I find it much more readable, but I can change it if you'd rather have all the examples follow the same basic structure.

adds(nodejs): storage cleaner

---

dotnet/hello-world/.gitignore
dotnet/hello-world/HelloWorld.csproj
dotnet/hello-world/Program.cs
dotnet/hello-world/README.md

Hello,
This PR contains a demo hellowr world app for #47 
Please check and give me headsup if something is to be fixed :)

feat: Add hello world function for .NET

---

dotnet/fcm-push-notifications/FCMPushNotifications.csproj
dotnet/fcm-push-notifications/Program.cs
dotnet/fcm-push-notifications/README.md

Hello,
This PR adds a sample for FCM push notification sending. The sample uses official FCM lib for c#. Some setup is also needed other than just uploading the func but I hope the instructions are clear. 
Please let me know if something needs to be polished :)

Feat add fcm push notification sample to dotnet

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/documentation.yaml
.github/ISSUE_TEMPLATE/feature.yaml

This PR creates Issue templates using the GitHub Issue Forms.
**Fixes** #99

Create Issue templates using GitHub Issue Forms

---

nodejs/subscribe-to-mailchimp/README.md
nodejs/subscribe-to-mailchimp/index.js
nodejs/subscribe-to-mailchimp/package.json

Resolves: appwrite/appwrite#1914

demo function for mailchimp subscribe

---

python/get-covid-stats/README.md
python/get-covid-stats/main.py
python/get-covid-stats/requirements.txt

Function fetching covid-19 stats.
Function takes country code, validates it, and returns stats for the country. If no country code was supplied, returns stats for global. Tested locally from Appwrite Console: ![screenshot](https://github-misc.s3.amazonaws.com/covid-func-test.png)
Implements python version of appwrite/appwrite#1923

Feat implement get covid stats python

---

deno/send-request/README.md
deno/send-request/index.js

towards https://github.com/appwrite/appwrite/issues/1921
Execution:
Stdout:

feat(deno): implement send-request function

---

java/generate-giphy-gif/.gitignore
java/generate-giphy-gif/README.md
java/generate-giphy-gif/pom.xml
java/generate-giphy-gif/src/main/java/GenerateGiphyGif.java
java/generate-giphy-gif/src/main/java/META-INF/MANIFEST.MF

This PR implements the `generateGiphyGif` function in Java.
This function takes a keyword as an input, use it as a keyword for Giphy API search, pick the first gif and return gif URL.
Implementation of the issue https://github.com/appwrite/appwrite/issues/1922
- Executed function
- Execution log

Feat implement generate giphy gif java

---

php/generate-giphy-gif/README.md
php/generate-giphy-gif/composer.json
php/generate-giphy-gif/index.php

Implements a demo function: Generate Giphy GIF
Implementation of the issue https://github.com/appwrite/appwrite/issues/1922

Feat generate Giphy GIF demo function - PHP

---

deno/prune-documents/README.md
deno/prune-documents/mod.ts

Created pruneDocuments cloud function in deno at prune-documents folder
Tasks summary:
Issue: [#1898](https://github.com/appwrite/appwrite/issues/1898)
Collection before execute:
Collection after execute:
Fucntion output:

Feat(pruneDocuments): implement prune documents deno

---

nodejs/send-message-bird-whatsapp-msg/README.md
nodejs/send-message-bird-whatsapp-msg/index.js
nodejs/send-message-bird-whatsapp-msg/package.json

Sending a custom Whatsapp Message to a given phone number using Messagebird API.
appwrite/appwrite#1891

Feat implement send message bird whatsapp msg node

---

deno/generate-gdpr-export/README.md
deno/generate-gdpr-export/mod.ts

Created generateGdprExport() cloud function in deno at generate-gdpr-export folder
Tasks summary:
Issue: [#1904](https://github.com/appwrite/appwrite/issues/1904)
Collection example:
Function output:
Generated files:
* Only exported 1 documents because user only create one document.

Feat(generateGdprExport): implement generate gdpr export deno

---

kotlin/tweet-new-membership/.gitignore
kotlin/tweet-new-membership/README.md
kotlin/tweet-new-membership/build.gradle.kts
kotlin/tweet-new-membership/gradle.properties
kotlin/tweet-new-membership/settings.gradle.kts
kotlin/tweet-new-membership/src/main/kotlin/Main.kt
kotlin/tweet-new-membership/src/main/kotlin/models/Membership.kt
kotlin/tweet-new-membership/src/main/kotlin/utils/Env.kt

This function triggers on `team.membership.create` event, and post a tweet that a new user joined a team.
Implements Kotlin version of appwrite/appwrite#1918

Feature: implement tweet new membership using kotlin

---

swift/add-created-at/.gitignore
swift/add-created-at/Package.swift
swift/add-created-at/README.md
swift/add-created-at/Sources/AddCreatedAt/main.swift

Part of appwrite/appwrite#1899
**Document input**
**Execution logs**
**Execution output**
**Final document**
**Document input**
**Execution logs**
**Execution output**

Implement addCreatedAt function in Swift

---

dotnet/send-message-bird-sms/.gitignore
dotnet/send-message-bird-sms/Program.cs
dotnet/send-message-bird-sms/README.md
dotnet/send-message-bird-sms/send-message-bird-sms.csproj

Addresses https://github.com/appwrite/appwrite/issues/1892

feat: implement send SMS using MessageBird API

---

deno/generate-google-map/README.md
deno/generate-google-map/mod.js

Ref: appwrite/appwrite#1905
Execution log:
Generated file:

Initial implementation of generate-google-map in Deno

---

ruby/add-updated-at/Gemfile
ruby/add-updated-at/Gemfile.lock
ruby/add-updated-at/README.md
ruby/add-updated-at/main.rb

Ref: appwrite/appwrite#1900
Document before update:
After updating:
Function log:

Initial implementation of add-updated-at in Ruby

---

ruby/send-message-bird-voice-msg/Gemfile
ruby/send-message-bird-voice-msg/Gemfile.lock
ruby/send-message-bird-voice-msg/README.md
ruby/send-message-bird-voice-msg/main.rb

addresses https://github.com/appwrite/appwrite/issues/1893

feat: implement send message bird voice msg

---

ruby/send-sms/Gemfile
ruby/send-sms/README.md
ruby/send-sms/main.rb

Resolves: #92
Implemented ruby cloud function to send SMS to other user's phone number.

feat: implement ruby cloud function to send sms

---

ruby/translate-text/Gemfile
ruby/translate-text/README.md
ruby/translate-text/main.rb

Resolves: #97 
Implemented ruby cloud function for translating text from one language to another using google translate.

feat: implement ruby cloud function to translate text

---

python/add-created-at/README.md
python/add-created-at/main.py
python/add-created-at/requirements.txt

Add a python function to set timestamp on doc creation.
Relates: https://github.com/appwrite/appwrite/issues/1899

Implement Python Function to Set Created At Timestamp

---

ruby/get-internet-speed/Gemfile
ruby/get-internet-speed/README.md
ruby/get-internet-speed/main.rb

Resolves: #89
Implemented ruby cloud function for checking internet download and upload speed.

feat: implement ruby cloud function to check internet speed

---

CONTRIBUTING.md

added a CONTRIBUTING.md (it is the same as the one in the main repo)

feat: Added  CONTRIBUTING.md

---

php/convert-cloud-convert-file/README.md
php/convert-cloud-convert-file/composer.json
php/convert-cloud-convert-file/index.php

Part of [appwrite/appwrite#1933](https://github.com/appwrite/appwrite/issues/1933)

Feat implement convert cloud convert file php
